sudo: required
services:
  - docker

before_install:
  - docker build -t jstran97/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jstran97/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-west-1-849628501123"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
